part of 'saca_localizer.dart';

const _english = <String, String>{
  'splashSubtitle': 'Offline triage support',
  'languageTitle': 'Choose your language / Yawu nyawa',
  'languageSubtitle': 'SACA health check. SACA jangany nyawa.',
  'languageGurindjiLabel': 'Gurindji',
  'languageGurindjiDescription': 'Gurindji yawu nyawa.',
  'languageEnglishLabel': 'English',
  'languageEnglishDescription': 'Use English labels and questions.',
  'languageFootnote':
      'This app gives preliminary guidance only. SACA jangany nyawa. Nyangu-nyangu-wangu.',
  'inputTitle': 'How do you want to enter symptoms?',
  'inputSubtitle': 'Choose one way to start.',
  'textInput': 'Text input',
  'textInputDescription': 'Type symptoms in simple words, such as fever.',
  'voiceInput': 'Voice input',
  'voiceInputDescription': 'Record speech offline, then review the transcript.',
  'visualSelection': 'Body map',
  'visualSelectionDescription': 'Pick symptoms on a body guide.',
  'voiceTitle': 'Voice input',
  'voiceSubtitle':
      'Speak clearly. Review and edit the transcript before continuing.',
  'voicePreparingTitle': 'Getting voice ready',
  'voicePreparingSubtitle': 'Please wait a moment.',
  'voiceTranscribingTitle': 'Listening to your recording',
  'voiceTranscribingSubtitle': 'Turning speech into text offline.',
  'stopRecording': 'Stop recording',
  'record': 'Record',
  'transcriptPlaceholder': 'Transcript will appear here.',
  'offlineSpeechNotice':
      'Offline speech recognition can make mistakes. Please check it.',
  'voiceAccuracyNotice':
      'Gurindji speech recognition is placeholder only. Please review the transcript or use text/visual input.',
  'useTranscript': 'Use transcript',
  'answerByVoice': 'Answer by voice',
  'stopVoiceAnswer': 'Stop voice answer',
  'voiceAnswerHeard': 'Heard:',
  'voiceAnswerRetry': 'Try again',
  'voiceAnswerNotMatched': 'Could not match answer. Please tap or try again.',
  'textTitle': 'Text input',
  'textSubtitle':
      'Write the main symptom first. The next screens ask for details.',
  'textPlaceholder': 'Example: fever',
  'visualTitle': 'Visual symptom selection',
  'visualSubtitle': 'Choose symptoms first, then mark pain locations.',
  'visualSymptomsTitle': 'Select your symptoms',
  'visualSymptomsSubtitle':
      'Tap one or more common symptoms. Use Other if it is not listed.',
  'visualOtherTitle': 'Other symptom',
  'visualOtherSubtitle': 'Describe it with text instead.',
  'visualFrontTitle': 'Any pain on the front?',
  'visualFrontSubtitle':
      'Tap extra pain locations on the front view, or continue.',
  'visualBackTitle': 'Any pain on the back?',
  'visualBackSubtitle':
      'Tap extra pain locations on the back view, or continue.',
  'visualStageSymptoms': 'Symptom',
  'visualStageFront': 'Front',
  'visualStageBack': 'Back',
  'visualSkipTitle': 'You can choose more than one area.',
  'selected': 'Selected',
  'selectedEmpty': 'No symptoms or body areas selected yet.',
  'severityTitle': 'How bad is the pain or symptom?',
  'severitySubtitle': 'Slide from 1 = very mild to 10 = severe or emergency.',
  'durationTitle': 'How long has it been happening?',
  'durationSubtitle': 'Pick the closest answer.',
  'relatedTitle': 'Any related symptoms?',
  'relatedSubtitle': 'Select all that apply.',
  'medicationTitle': 'Have you taken medicine?',
  'medicationSubtitle': 'This helps avoid unsafe advice.',
  'foodTitle': 'Any recent food changes?',
  'foodSubtitle': 'Think about the last day or two.',
  'allergiesTitle': 'Any possible allergies?',
  'allergiesSubtitle':
      'Food, medicine, insects, or something in the environment.',
  'healthChangesTitle': 'Any recent health or lifestyle changes?',
  'healthChangesSubtitle':
      'This includes sleep, stress, travel, or sick contacts.',
  'continue': 'Continue',
  'analyse': 'Analyse',
  'analysingTitle': 'Analysing',
  'analysingSubtitle': 'Checking symptoms with the offline placeholder model.',
  'noResultTitle': 'No result available',
  'noResultSubtitle': 'Please go back and run the analysis again.',
  'back': 'Back',
  'resultTitle': 'Care guidance',
  'resultSubtitle':
      'Check the possible condition, severity, and recommended next step.',
  'finish': 'Finish',
  'startAgain': 'Start again',
  'offlineReady': 'Offline ready',
  'languageStatus': 'Language',
  'notSelected': 'Not selected',
  'assessmentFlow': 'Assessment flow',
  'progressLanguage': 'Language',
  'progressInput': 'Input',
  'progressQuestions': 'Questions',
  'progressAnalysis': 'Analysis',
  'progressResult': 'Result',
  'noPersonalInfo': 'No personal information is stored.',
  'infoTitle': 'SACA prototype',
  'infoContent':
      'SACA is an offline triage support prototype for the Kalkaringi and Daguragu context. It is not a diagnostic tool.',
  'ok': 'OK',
  'call000Now': 'Call 000 now',
  'possiblePattern': 'Possible condition',
  'recommendations': 'Recommendations',
  'severity': 'Severity',
  'severityMild': 'Mild',
  'severityModerate': 'Moderate',
  'severitySevere': 'Severe',
  'severityEmergency': 'Emergency',
  'bodyAreaSemantic': 'Body area',
  'errorGeneric': 'Something went wrong. Please try again.',
  'disclaimer':
      'SACA provides preliminary triage guidance only. It does not replace a clinician.',
};

const _gurindji = <String, String>{
  'splashSubtitle': 'Jangany nyawa',
  'languageTitle': 'Choose your language / Yawu nyawa',
  'languageSubtitle': 'English nyawa. Gurindji nyawa.',
  'languageGurindjiLabel': 'Gurindji',
  'languageGurindjiDescription': 'Gurindji yawu nyawa.',
  'languageEnglishLabel': 'English',
  'languageEnglishDescription': 'Use English labels and questions.',
  'languageFootnote': 'SACA jangany nyawa. Nyangu-nyangu-wangu.',
  'inputTitle': 'Nyatpa jangany nyawa?',
  'inputSubtitle': 'Nyawa yawu. Nyawa puya. Nyawa ngayirrp.',
  'textInput': 'Yawu',
  'textInputDescription': 'Jangany yawu nyawa.',
  'voiceInput': 'Ngayirrp',
  'voiceInputDescription': 'Ngayirrp nyawa. Yawu nyawa.',
  'visualSelection': 'Puya nyawa',
  'visualSelectionDescription': 'Jangany puya nyawa.',
  'voiceTitle': 'Ngayirrp',
  'voiceSubtitle': 'Ngayirrp yamak. Yawu nyawa jala.',
  'voicePreparingTitle': 'Ngayirrp yamak',
  'voicePreparingSubtitle': 'Pirri-pirri.',
  'voiceTranscribingTitle': 'Ngayirrp nyawa',
  'voiceTranscribingSubtitle': 'Yawu jala.',
  'stopRecording': 'Kurtirni',
  'record': 'Ngayirrp',
  'transcriptPlaceholder': 'Yawu jala karrinyana.',
  'offlineSpeechNotice': 'Ngayirrp yawu mayi. Yawu nyawa.',
  'voiceAccuracyNotice': 'Gurindji ngayirrp mayi. Yawu nyawa.',
  'useTranscript': 'Yawu nyawa',
  'answerByVoice': 'Ngayirrp answer',
  'stopVoiceAnswer': 'Kurtirni answer',
  'voiceAnswerHeard': 'Yawu:',
  'voiceAnswerRetry': 'Ngayirrp jala',
  'voiceAnswerNotMatched': 'Yawu karrwarn. Tap nyawa or ngayirrp jala.',
  'textTitle': 'Yawu',
  'textSubtitle': 'Jangany yawu nyawa. Ngana yawu nyawa kaput.',
  'textPlaceholder': 'makurrmakurr',
  'visualTitle': 'Jangany nyawa',
  'visualSubtitle': 'Jangany nyawa, puya nyawa.',
  'visualSymptomsTitle': 'Nyatpa jangany?',
  'visualSymptomsSubtitle': 'Jangany kirri nyawa. Other nyawa yawu-kari.',
  'visualOtherTitle': 'Other symptom',
  'visualOtherSubtitle': 'Yawu-kari.',
  'visualFrontTitle': 'Front puya janga?',
  'visualFrontSubtitle': 'Front puya nyawa, yuwa kawayi.',
  'visualBackTitle': 'Back puya janga?',
  'visualBackSubtitle': 'Back puya nyawa, yuwa kawayi.',
  'visualStageSymptoms': 'Jangany',
  'visualStageFront': 'Front',
  'visualStageBack': 'Back',
  'visualSkipTitle': 'Puya kirri nyawa.',
  'selected': 'Nyawa',
  'selectedEmpty': 'Jangany puya karrwarn.',
  'severityTitle': 'Jangany nyatpa strong?',
  'severitySubtitle': '1 = yamak, 10 = 000 janga.',
  'durationTitle': 'Nyangurla jala?',
  'durationSubtitle': 'Tirrip nyawa.',
  'relatedTitle': 'Jangany kirri?',
  'relatedSubtitle': 'Nyawa.',
  'medicationTitle': 'Mirrijin nyawa?',
  'medicationSubtitle': 'Mirrijin yamak nyawa.',
  'foodTitle': 'Mangarri jala?',
  'foodSubtitle': 'Jala puriny nyawa.',
  'allergiesTitle': 'Mawuya nyawa?',
  'allergiesSubtitle': 'Mangarri, mirrijin, mawuya nyawa.',
  'healthChangesTitle': 'Puya jala?',
  'healthChangesSubtitle': 'Makin, yawarra, kawayi nyawa.',
  'continue': 'Kawayi',
  'analyse': 'Nyawa',
  'analysingTitle': 'Nyawa jala',
  'analysingSubtitle': 'SACA jangany nyawa.',
  'noResultTitle': 'Nyawa karrwarn',
  'noResultSubtitle': 'Wart nyawa.',
  'back': 'Wart',
  'resultTitle': 'Jangany nyawa',
  'resultSubtitle': 'Kawayi nyawa.',
  'finish': 'Yuwa',
  'startAgain': 'Jala nyawa',
  'offlineReady': 'Yamak',
  'languageStatus': 'Yawu',
  'notSelected': 'Karrwarn',
  'assessmentFlow': 'Jangany yanku',
  'progressLanguage': 'Yawu',
  'progressInput': 'Nyawa',
  'progressQuestions': 'Nyampa',
  'progressAnalysis': 'Jangany',
  'progressResult': 'Kawayi',
  'noPersonalInfo': 'Yini karrwarn.',
  'infoTitle': 'SACA',
  'infoContent': 'SACA jangany nyawa Kalkaringi Daguragu. Nyangu-nyangu-wangu.',
  'ok': 'Yuwa',
  'call000Now': '000 kawayi jala',
  'possiblePattern': 'Possible condition',
  'recommendations': 'Kawayi nyawa',
  'severity': 'Jangany',
  'severityMild': 'Yamak',
  'severityModerate': 'Janga',
  'severitySevere': 'Warlarrp',
  'severityEmergency': '000',
  'bodyAreaSemantic': 'Puya',
  'errorGeneric': 'Nyawa karrwarn. Kawayi nyawa.',
  'disclaimer': 'SACA jangany nyawa. Nyangu-nyangu-wangu.',
};

const _englishChoiceLabels = <String, String>{
  'less than one day': '<1 day',
  'one to three days': '1-3 days',
  'four to seven days': '4-7 days',
  'more than seven days': '>7 days',
  'no medication': 'No',
  'taken medication': 'Yes',
  'not sure medication': 'Not sure',
  'no food change': 'No change',
  'unfamiliar food': 'Unfamiliar food',
  'skipped meals': 'Skipped meals',
  'not sure food': 'Not sure',
  'no known allergies': 'No known allergies',
  'possible allergies': 'Yes',
  'not sure allergies': 'Not sure',
  'no recent health change': 'No change',
  'sick contact or travel': 'Sick contact or travel',
  'sleep or stress change': 'Sleep or stress change',
  'not sure health change': 'Not sure',
};

const _gurindjiChoiceLabels = <String, String>{
  'less than one day': '<1 tirrip',
  'one to three days': '1-3 tirrip',
  'four to seven days': '4-7 tirrip',
  'more than seven days': '>7 tirrip',
  'no medication': 'Karrwarn',
  'taken medication': 'Yuwa',
  'not sure medication': 'Mayi',
  'no food change': 'Karrwarn',
  'unfamiliar food': 'Mangarri jalayalang',
  'skipped meals': 'Mangarri karrwarn',
  'not sure food': 'Mayi',
  'no known allergies': 'Karrwarn',
  'possible allergies': 'Mayi',
  'not sure allergies': 'Mayi',
  'no recent health change': 'Karrwarn',
  'sick contact or travel': 'Janga kawayi',
  'sleep or stress change': 'Makin mayi',
  'not sure health change': 'Mayi',
};

const _gurindjiSymptomFallbacks = <String, String>{
  'none': 'Karrwarn',
  'breathing_trouble': 'ngayirrp ma-',
  'bloating': 'majul rumpa',
  'rash': 'warrgarrk marntara',
};

const _gurindjiBodyFallbacks = <String, String>{
  'head': 'ngarlaka',
  'eyes': 'mila',
  'throat': 'ngirlkirri',
  'heart': 'mangarli',
  'chest': 'mangarli',
  'stomach': 'majul',
  'hand': 'marla',
  'leg': 'kurtpu',
  'knees': 'tingarri',
  'toes': 'jamana nantananta',
  'ears': 'langa',
  'neck': 'wirri',
  'shoulder': 'laja',
  'back': 'parntawurru',
  'arm': 'murna',
  'finger': 'wartan nantananta',
  'ankle': 'tari',
  'lower_back': 'parntawurru',
  'lower_leg': 'kurtpu',
};

const _gurindjiDiseaseLabels = <String, String>{
  'Influenza': 'makurrmakurr / ngirlkirri pung',
  'Stomach upset': 'majul pung / kurlpak yuwa-',
  'General symptoms': 'puya pung / jangany',
  'Urgent symptoms': 'mangarli pung / ngayirrp ma- / warlarrp',
};

const _englishDiseaseLabels = <String, String>{
  'Influenza': 'Fever and throat symptoms',
  'Stomach upset': 'Stomach symptoms',
  'General symptoms': 'Pain or body discomfort',
  'Urgent symptoms': 'Urgent chest, breathing, or bleeding signs',
};

const _englishGuidance = <String, List<String>>{
  'Influenza': [
    'Rest and drink water.',
    'Use fever relief if it is safe for you.',
    'Visit the clinic if fever, throat pain, or weakness gets worse.',
    'Get urgent help if breathing becomes hard.',
  ],
  'Stomach upset': [
    'Sip water often.',
    'Avoid heavy meals for now.',
    'Visit the clinic if pain or vomiting keeps going.',
    'Get urgent help if you cannot keep fluids down.',
  ],
  'General symptoms': [
    'Rest and watch for changes.',
    'Write down where it hurts and what changed.',
    'Visit the clinic if the pain keeps going or gets stronger.',
    'Get urgent help for chest pain, trouble breathing, or bleeding.',
  ],
  'Urgent symptoms': [
    'Call 000 now.',
    'Get help from someone nearby if possible.',
    'Do not wait for the app if breathing, chest pain, or bleeding is severe.',
  ],
};

const _gurindjiGuidance = <String, List<String>>{
  'Influenza': [
    'Yawarra.',
    'Mirrijin yamak nyawa.',
    'Nyangu-nyangu kawayi jangany warlarrp.',
    'Ngurra-ngkurra yamak.',
  ],
  'Stomach upset': [
    'Yawarra.',
    'Mangarri yamak.',
    'Nyangu-nyangu kawayi jangany warlarrp.',
  ],
  'General symptoms': [
    'Yawarra.',
    'Jangany nyawa jala.',
    'Nyangu-nyangu kawayi jangany warlarrp.',
  ],
  'Urgent symptoms': [
    '000 kawayi jala.',
    'SACA nyawa-wangu.',
    'Yamak karrinyana.',
  ],
};
