part of 'saca_localizer.dart';

const _english = <String, String>{
  'splashSubtitle': 'Offline triage support',
  'languageTitle': 'Choose your language / Yawu nyawa',
  'languageSubtitle': 'SACA health check. SACA jangany nyawa.',
  'languageGurindjiLabel': 'Gurindji',
  'languageGurindjiDescription': 'Gurindji yawu nyawa.',
  'languageEnglishLabel': 'English',
  'languageEnglishDescription': 'Use English labels and questions.',
  'languageFootnote':
      'This app gives preliminary guidance only. SACA jangany nyawa. Nyangu-nyangu-wangu.',
  'inputTitle': 'How do you want to enter symptoms?',
  'inputSubtitle': 'Choose one way to start.',
  'textInput': 'Text input',
  'textInputDescription': 'Type symptoms in simple words, such as fever.',
  'voiceInput': 'Voice input',
  'voiceInputDescription': 'Record speech offline, then review the transcript.',
  'visualSelection': 'Body map',
  'visualSelectionDescription': 'Pick symptoms on a body guide.',
  'voiceTitle': 'Voice input',
  'voiceSubtitle':
      'Speak clearly. Review and edit the transcript before continuing.',
  'voicePreparingTitle': 'Getting voice ready',
  'voicePreparingSubtitle': 'Please wait a moment.',
  'voiceTranscribingTitle': 'Listening to your recording',
  'voiceTranscribingSubtitle': 'Turning speech into text offline.',
  'stopRecording': 'Stop recording',
  'stop': 'Stop',
  'record': 'Record',
  'transcriptPreview': 'Transcript preview',
  'recordingNow': 'Recording... speak now',
  'transcriptPlaceholder': 'Transcript will appear here.',
  'offlineSpeechNotice':
      'Offline speech recognition can make mistakes. Please check it.',
  'voiceDraftFallbackNotice':
      'Final transcription could not be confirmed. Please review the draft before continuing.',
  'voiceAccuracyNotice':
      'Gurindji speech recognition is placeholder only. Please review the transcript or use text/visual input.',
  'useTranscript': 'Use transcript',
  'answerByVoice': 'Answer by voice',
  'stopVoiceAnswer': 'Stop voice answer',
  'voiceAnswerHeard': 'Heard:',
  'voiceAnswerRetry': 'Try again',
  'voiceAnswerNotMatched': 'Could not match answer. Please tap or try again.',
  'textTitle': 'Text input',
  'textSubtitle':
      'Write the main symptom first. The next screens ask for details.',
  'textPlaceholder': 'Example: fever',
  'visualTitle': 'Visual symptom selection',
  'visualSubtitle': 'Choose symptoms first, then mark pain locations.',
  'visualSymptomsTitle': 'Select your symptoms',
  'visualSymptomsSubtitle':
      'Tap one or more common symptoms. Use Other if it is not listed.',
  'visualOtherTitle': 'Other symptom',
  'visualOtherSubtitle': 'Describe it with text instead.',
  'visualFrontTitle': 'Any pain on the front?',
  'visualFrontSubtitle':
      'Tap extra pain locations on the front view, or continue.',
  'visualBackTitle': 'Any pain on the back?',
  'visualBackSubtitle':
      'Tap extra pain locations on the back view, or continue.',
  'visualStageSymptoms': 'Symptom',
  'visualStageFront': 'Front',
  'visualStageBack': 'Back',
  'visualSkipTitle': 'You can choose more than one area.',
  'selected': 'Selected',
  'selectedEmpty': 'No symptoms or body areas selected yet.',
  'severityTitle': 'How bad is the pain or symptom?',
  'severitySubtitle': 'Slide from 1 = very mild to 10 = severe or emergency.',
  'severityDescriptorLow': 'Low pain',
  'severityDescriptorModerate': 'Moderate pain',
  'severityDescriptorHigh': 'High pain',
  'severityDescriptorEmergency': 'Emergency level',
  'durationTitle': 'How long has it been happening?',
  'durationSubtitle': 'Pick the closest answer.',
  'relatedTitle': 'Any related symptoms?',
  'relatedSubtitle': 'Select all that apply.',
  'suggestedFromFirstSymptom':
      'Suggested from your first symptom and likely condition.',
  'suggestedFromVoiceCues': 'Suggested from voice cues. Please review.',
  'suggestionHint': 'Suggested items appear first. Add anything else below.',
  'selectedNow': 'Selected now',
  'noneSelectedYet': 'Nothing selected yet.',
  'relatedOtherPlaceholder': 'Other symptom',
  'emptyInputConfirmTitle': 'No clear symptom heard',
  'emptyInputConfirmMessage':
      'SACA did not receive enough symptom information. Please record again or type a symptom before continuing.',
  'noClearIllnessConfirmTitle': 'No clear illness found',
  'noClearIllnessConfirmMessage':
      'SACA could not match a clear illness from the information provided. You can review your answers or continue to general guidance.',
  'reviewAnswers': 'Review answers',
  'continueAnyway': 'Continue anyway',
  'medicationTitle': 'Have you taken medicine?',
  'medicationSubtitle': 'This helps avoid unsafe advice.',
  'foodTitle': 'Any recent food changes?',
  'foodSubtitle': 'Think about the last day or two.',
  'allergiesTitle': 'Any possible allergies?',
  'allergiesSubtitle':
      'Food, medicine, insects, or something in the environment.',
  'healthChangesTitle': 'Any recent health or lifestyle changes?',
  'healthChangesSubtitle':
      'This includes sleep, stress, travel, or sick contacts.',
  'continue': 'Continue',
  'skip': 'Skip',
  'analyse': 'Analyse',
  'reviewTitle': 'Review your information',
  'reviewSubtitle': 'Check details before SACA analyses them.',
  'reviewInput': 'Symptoms and body areas',
  'reviewQuestions': 'Follow-up answers',
  'edit': 'Edit',
  'addMoreInfo': 'Add more information',
  'addMoreLimit': 'Information limit reached',
  'bestMatch': 'Best match',
  'bestMatchFromAnswers': 'Best match from your answers',
  'alsoPossible': 'Also possible',
  'lessLikely': 'Less likely',
  'otherPossibilities': 'Other possibilities to discuss',
  'confidenceWarning':
      'The app is not confident yet. Add more symptoms or ask a clinician if you are worried.',
  'analysingTitle': 'Analysing',
  'analysingSubtitle': 'Checking symptoms with the offline placeholder model.',
  'noResultTitle': 'No result available',
  'noResultSubtitle': 'Please go back and run the analysis again.',
  'back': 'Back',
  'resultTitle': 'Care guidance',
  'resultSubtitle':
      'Check the possible condition, severity, and recommended next step.',
  'finish': 'Finish',
  'startAgain': 'Start again',
  'offlineReady': 'Offline ready',
  'offlineNotReady': 'Not ready',
  'languageStatus': 'Language',
  'notSelected': 'Not selected',
  'settingsLabel': 'Settings',
  'infoLabel': 'Prototype information',
  'assessmentFlow': 'Assessment flow',
  'progressLanguage': 'Language',
  'progressInput': 'Input',
  'progressQuestions': 'Questions',
  'progressAnalysis': 'Analysis',
  'progressResult': 'Result',
  'noPersonalInfo': 'No personal information is stored.',
  'infoTitle': 'SACA prototype',
  'infoContent':
      'SACA is an offline triage support prototype for the Kalkaringi and Daguragu context. It is not a diagnostic tool.',
  'settingsTitle': 'Settings',
  'settingsSubtitle': 'Adjust language and appearance.',
  'settingsLanguageTitle': 'Language',
  'settingsLanguageSubtitle': 'Choose the app language.',
  'settingsAppearanceTitle': 'Appearance',
  'settingsThemeStyleTitle': 'Theme',
  'settingsThemeStyleSubtitle': 'Choose the visual style for SACA.',
  'settingsThemeModern': 'Modern (Default)',
  'settingsThemeGlass': 'Glass (Preview)',
  'settingsThemeClassic': 'Classic',
  'settingsThemeGlassFallback':
      'Glass preview is unavailable on this device. Modern is shown instead.',
  'settingsLight': 'Light',
  'settingsDark': 'Dark',
  'settingsSystem': 'System',
  'settingsTextSizeTitle': 'Text size',
  'settingsTextScale': 'Text scale',
  'settingsTextPreview':
      'Preview: larger text helps patients read instructions clearly.',
  'settingsDone': 'Done',
  'ok': 'OK',
  'call000Now': 'Call 000 now',
  'possiblePattern': 'Possible explanations, not a diagnosis',
  'possiblePatternHelper':
      'These are ranked possibilities based on your answers. You may not have all of them.',
  'resultNextStepNote':
      'Use this to decide next steps, not as a final diagnosis.',
  'recommendations': 'Recommendations',
  'severity': 'Severity',
  'severityMild': 'Mild',
  'severityModerate': 'Moderate',
  'severitySevere': 'Severe',
  'severityEmergency': 'Emergency',
  'bodyAreaSemantic': 'Body area',
  'errorGeneric': 'Something went wrong. Please try again.',
  'disclaimer':
      'SACA provides preliminary triage guidance only. It does not replace a clinician.',
};

const _gurindji = <String, String>{
  'splashSubtitle': 'Jangany nyawa',
  'languageTitle': 'Choose your language / Yawu nyawa',
  'languageSubtitle': 'Yawu nyawa.',
  'languageGurindjiLabel': 'Gurindji',
  'languageGurindjiDescription': 'Gurindji yawu nyawa.',
  'languageEnglishLabel': 'Kartiya yawu',
  'languageEnglishDescription': 'Kartiya yawu nyawa.',
  'languageFootnote': 'SACA jangany nyawa. Nyangu-nyangu-wangu.',
  'inputTitle': 'Nyatpa jangany nyawa?',
  'inputSubtitle': 'Nyawa yawu. Nyawa puya. Nyawa ngayirrp.',
  'textInput': 'Yawu',
  'textInputDescription': 'Jangany yawu nyawa.',
  'voiceInput': 'Ngayirrp',
  'voiceInputDescription': 'Ngayirrp nyawa. Yawu nyawa.',
  'visualSelection': 'Puya nyawa',
  'visualSelectionDescription': 'Jangany puya nyawa.',
  'voiceTitle': 'Ngayirrp',
  'voiceSubtitle': 'Ngayirrp yamak. Yawu nyawa jala.',
  'voicePreparingTitle': 'Ngayirrp yamak',
  'voicePreparingSubtitle': 'Pirri-pirri.',
  'voiceTranscribingTitle': 'Ngayirrp nyawa',
  'voiceTranscribingSubtitle': 'Yawu jala.',
  'stopRecording': 'Kurtirni',
  'stop': 'Kurtirni',
  'record': 'Ngayirrp',
  'transcriptPreview': 'Transcript preview',
  'recordingNow': 'Ngayirrp jala',
  'transcriptPlaceholder': 'Yawu jala karrinyana.',
  'offlineSpeechNotice': 'Ngayirrp yawu mayi. Yawu nyawa.',
  'voiceDraftFallbackNotice': 'Yawu nyawa. Ngumpit mayi yawu ngantipkarra.',
  'voiceAccuracyNotice': 'Gurindji ngayirrp mayi. Yawu nyawa.',
  'useTranscript': 'Yawu nyawa',
  'answerByVoice': 'Ngayirrp jangat',
  'stopVoiceAnswer': 'Jangat kurtirni',
  'voiceAnswerHeard': 'Yawu:',
  'voiceAnswerRetry': 'Ngayirrp jala',
  'voiceAnswerNotMatched': 'Yawu karrwarn. Tap nyawa or ngayirrp jala.',
  'textTitle': 'Yawu',
  'textSubtitle': 'Jangany yawu nyawa. Ngana yawu nyawa kaput.',
  'textPlaceholder': 'makurrmakurr',
  'visualTitle': 'Jangany nyawa',
  'visualSubtitle': 'Jangany nyawa, puya nyawa.',
  'visualSymptomsTitle': 'Nyatpa jangany?',
  'visualSymptomsSubtitle': 'Jangany kirri nyawa. Yawu-kari nyawa.',
  'visualOtherTitle': 'Yawu-kari jangany',
  'visualOtherSubtitle': 'Yawu-kari.',
  'visualFrontTitle': 'Kamparra puya janga?',
  'visualFrontSubtitle': 'Kamparra puya nyawa, yuwa kawayi.',
  'visualBackTitle': 'Parntawurru puya janga?',
  'visualBackSubtitle': 'Parntawurru puya nyawa, yuwa kawayi.',
  'visualStageSymptoms': 'Jangany',
  'visualStageFront': 'Kamparra',
  'visualStageBack': 'Parntawurru',
  'visualSkipTitle': 'Puya kirri nyawa.',
  'selected': 'Nyawa',
  'selectedEmpty': 'Jangany puya karrwarn.',
  'severityTitle': 'Jangany nyatpa warlarrp?',
  'severitySubtitle': '1 = yamak, 10 = 000 janga.',
  'severityDescriptorLow': 'Jangany kurlang',
  'severityDescriptorModerate': 'Jangany janga',
  'severityDescriptorHigh': 'Jangany warlarrp',
  'severityDescriptorEmergency': '000 janga',
  'durationTitle': 'Nyangurla jala?',
  'durationSubtitle': 'Tirrip nyawa.',
  'relatedTitle': 'Jangany kirri?',
  'relatedSubtitle': 'Nyawa.',
  'suggestedFromFirstSymptom': 'Jangany nyawa jala.',
  'suggestedFromVoiceCues': 'Voice jala. Nyawa-rni.',
  'suggestionHint': 'Jangany nyawa. Yawu-kari kurru.',
  'selectedNow': 'Nyawa jala',
  'noneSelectedYet': 'Karrwarn.',
  'relatedOtherPlaceholder': 'Yawu-kari',
  'emptyInputConfirmTitle': 'Jangany nyawa-wangu',
  'emptyInputConfirmMessage':
      'SACA jangany nyawa-wangu. Record-rni or write-rni symptom.',
  'noClearIllnessConfirmTitle': 'Jangany clear-wangu',
  'noClearIllnessConfirmMessage':
      'SACA jangany clear-wangu. Nyawa-rni answers or continue-rni guidance.',
  'reviewAnswers': 'Nyawa answers',
  'continueAnyway': 'Continue',
  'medicationTitle': 'Mirrijin nyawa?',
  'medicationSubtitle': 'Mirrijin yamak nyawa.',
  'foodTitle': 'Mangarri jala?',
  'foodSubtitle': 'Jala puriny nyawa.',
  'allergiesTitle': 'Mawuya nyawa?',
  'allergiesSubtitle': 'Mangarri, mirrijin, mawuya nyawa.',
  'healthChangesTitle': 'Puya jala?',
  'healthChangesSubtitle': 'Makin, yawarra, kawayi nyawa.',
  'continue': 'Kawayi',
  'skip': 'Kawayi-wangu',
  'analyse': 'Nyawa',
  'reviewTitle': 'Yawu nyawa',
  'reviewSubtitle': 'Jangany nyawa jala.',
  'reviewInput': 'Jangany puya',
  'reviewQuestions': 'Nyampa jangat',
  'edit': 'Wart nyawa',
  'addMoreInfo': 'Yawu-kari kurru',
  'addMoreLimit': 'Yawu-kari karrwarn',
  'bestMatch': 'Best match',
  'bestMatchFromAnswers': 'Best match from your answers',
  'alsoPossible': 'Also possible',
  'lessLikely': 'Less likely',
  'otherPossibilities': 'Other possibilities to discuss',
  'confidenceWarning':
      'The app is not confident yet. Add more symptoms or ask a clinician if you are worried.',
  'analysingTitle': 'Nyawa jala',
  'analysingSubtitle': 'SACA jangany nyawa.',
  'noResultTitle': 'Nyawa karrwarn',
  'noResultSubtitle': 'Wart nyawa.',
  'back': 'Wart',
  'resultTitle': 'Jangany nyawa',
  'resultSubtitle': 'Kawayi nyawa.',
  'finish': 'Yuwa',
  'startAgain': 'Jala nyawa',
  'offlineReady': 'Yamak',
  'offlineNotReady': 'Karrwarn',
  'languageStatus': 'Yawu',
  'notSelected': 'Karrwarn',
  'settingsLabel': 'Nyawa',
  'infoLabel': 'SACA nyawa',
  'assessmentFlow': 'Jangany yanku',
  'progressLanguage': 'Yawu',
  'progressInput': 'Nyawa',
  'progressQuestions': 'Nyampa',
  'progressAnalysis': 'Jangany',
  'progressResult': 'Kawayi',
  'noPersonalInfo': 'Yini karrwarn.',
  'infoTitle': 'SACA',
  'infoContent': 'SACA jangany nyawa Kalkaringi Daguragu. Nyangu-nyangu-wangu.',
  'settingsTitle': 'Nyawa',
  'settingsSubtitle': 'Yawu warrkap nyawa.',
  'settingsLanguageTitle': 'Yawu',
  'settingsLanguageSubtitle': 'Yawu nyawa.',
  'settingsAppearanceTitle': 'Warrkap',
  'settingsThemeStyleTitle': 'Theme',
  'settingsThemeStyleSubtitle': 'Choose the visual style for SACA.',
  'settingsThemeModern': 'Modern (Default)',
  'settingsThemeGlass': 'Glass (Preview)',
  'settingsThemeClassic': 'Classic',
  'settingsThemeGlassFallback':
      'Glass preview is unavailable on this device. Modern is shown instead.',
  'settingsLight': 'Warlakap',
  'settingsDark': 'Karrap',
  'settingsSystem': 'Jalajala',
  'settingsTextSizeTitle': 'Yawu jangkarni',
  'settingsTextScale': 'Yawu jangkarni',
  'settingsTextPreview': 'Yawu warlak yamak nyawa.',
  'settingsDone': 'Yuwa',
  'ok': 'Yuwa',
  'call000Now': '000 kawayi jala',
  'possiblePattern': 'Possible explanations, not a diagnosis',
  'possiblePatternHelper':
      'These are ranked possibilities based on your answers. You may not have all of them.',
  'resultNextStepNote':
      'Use this to decide next steps, not as a final diagnosis.',
  'recommendations': 'Kawayi nyawa',
  'severity': 'Jangany',
  'severityMild': 'Yamak',
  'severityModerate': 'Janga',
  'severitySevere': 'Warlarrp',
  'severityEmergency': '000',
  'bodyAreaSemantic': 'Puya',
  'errorGeneric': 'Nyawa karrwarn. Kawayi nyawa.',
  'disclaimer': 'SACA jangany nyawa. Nyangu-nyangu-wangu.',
};

const _englishChoiceLabels = <String, String>{
  'less than one day': '<1 day',
  'one to three days': '1-3 days',
  'four to seven days': '4-7 days',
  'more than seven days': '>7 days',
  'no medication': 'No',
  'taken medication': 'Yes',
  'not sure medication': 'Not sure',
  'no food change': 'No change',
  'unfamiliar food': 'Unfamiliar food',
  'skipped meals': 'Skipped meals',
  'not sure food': 'Not sure',
  'no known allergies': 'No known allergies',
  'possible allergies': 'Yes',
  'not sure allergies': 'Not sure',
  'no recent health change': 'No change',
  'sick contact or travel': 'Sick contact or travel',
  'sleep or stress change': 'Sleep or stress change',
  'not sure health change': 'Not sure',
};

const _gurindjiChoiceLabels = <String, String>{
  'less than one day': '<1 tirrip',
  'one to three days': '1-3 tirrip',
  'four to seven days': '4-7 tirrip',
  'more than seven days': '>7 tirrip',
  'no medication': 'Karrwarn',
  'taken medication': 'Yuwa',
  'not sure medication': 'Mayi',
  'no food change': 'Karrwarn',
  'unfamiliar food': 'Mangarri jalayalang',
  'skipped meals': 'Mangarri karrwarn',
  'not sure food': 'Mayi',
  'no known allergies': 'Karrwarn',
  'possible allergies': 'Mayi',
  'not sure allergies': 'Mayi',
  'no recent health change': 'Karrwarn',
  'sick contact or travel': 'Janga kawayi',
  'sleep or stress change': 'Makin mayi',
  'not sure health change': 'Mayi',
};

const _gurindjiSymptomFallbacks = <String, String>{
  'none': 'Karrwarn',
  'breathing_trouble': 'ngayirrp ma-',
  'bloating': 'majul rumpa',
  'rash': 'warrgarrk marntara',
};

const _gurindjiBodyFallbacks = <String, String>{
  'head': 'ngarlaka',
  'eyes': 'mila',
  'throat': 'ngirlkirri',
  'heart': 'mangarli',
  'chest': 'mangarli',
  'stomach': 'majul',
  'hand': 'marla',
  'leg': 'kurtpu',
  'knees': 'tingarri',
  'toes': 'jamana nantananta',
  'ears': 'langa',
  'neck': 'wirri',
  'shoulder': 'laja',
  'back': 'parntawurru',
  'arm': 'murna',
  'finger': 'wartan nantananta',
  'ankle': 'tari',
  'lower_back': 'parntawurru',
  'lower_leg': 'kurtpu',
};

const _gurindjiGenericDiseaseLabel = 'jangany';

const _gurindjiDiseaseAliases = <String, String>{
  'uti': 'urinary tract infection',
  'asthma': 'bronchial asthma',
  'hemorrhoids': 'dimorphic hemorrhoids',
  'spondylosis': 'cervical spondylosis',
  'no clear illness detected': 'general symptoms',
  'pain symptoms': 'general symptoms',
  'skin irritation': 'skin symptoms',
};

const _gurindjiDiseaseLabels = <String, String>{
  'acne': 'warrgarrk marntara',
  'allergy': 'mayi jangany',
  'anemia': 'kungulu mayi',
  'anxiety': 'mangarli mayi',
  'arthritis': 'kuyuwarn pung',
  'bronchial asthma': 'ngayirrp ma-',
  'bronchitis': 'ngayirrp ma- / kulyurrk',
  'cervical spondylosis': 'wirri pung / kuyuwarn pung',
  'chicken pox': 'warrgarrk marntara / makurrmakurr',
  'chronic kidney disease': 'jiminkirt jangany',
  'common cold': 'makurru / kulykulya',
  'covid 19': 'makurrmakurr / kulyurrk / ngayirrp ma-',
  'dementia': 'mikilyi mayi',
  'dengue': 'makurrmakurr / kuyuwarn pung',
  'depression': 'mangarli mayi',
  'dermatitis': 'warrgarrk marntara',
  'diabetes': 'jangany',
  'dimorphic hemorrhoids': 'jawuljaru / jangany',
  'drug reaction': 'mirrijin jangany',
  'epilepsy': 'mikilyi jangany',
  'food poisoning': 'mangarri jangany / kurlpak yuwa-',
  'fungal infection': 'warrgarrk marntara',
  'gastritis': 'majul pung',
  'gastroesophageal reflux disease': 'majul pung / lirra pung',
  'general symptoms': 'puya pung / jangany',
  'heart disease': 'mangarli jangany',
  'hypertension': 'kungulu mayi / mangarli jangany',
  'impetigo': 'warrgarrk marntara',
  'influenza': 'makurrmakurr / ngirlkirri pung',
  'jaundice': 'malumpa jangany',
  'liver disease': 'malumpa jangany',
  'malaria': 'makurrmakurr / jangany',
  'migraine': 'ngarlaka pung',
  'obesity': 'murlpa mayi',
  'parkinson s': 'mikilyi jangany',
  'peptic ulcer disease': 'majul pung',
  'pneumonia': 'ngayirrp ma- / kulyurrk',
  'psoriasis': 'warrgarrk marntara',
  'sinusitis': 'jitji jangany',
  'skin symptoms': 'warrgarrk marntara',
  'stomach upset': 'majul pung / kurlpak yuwa-',
  'stroke': 'mikilyi jangany / warlarrp',
  'thyroid disorder': 'ngirlkirri jangany',
  'tuberculosis': 'ngayirrp ma- / kulyurrk',
  'typhoid': 'makurrmakurr / majul pung',
  'ulcer': 'majul pung',
  'urgent symptoms': 'mangarli pung / ngayirrp ma- / warlarrp',
  'urinary tract infection': 'jiminkirt jangany',
  'varicose veins': 'kampun jangany',
};

const _gurindjiDiseaseKeywordGuesses = <String, String>{
  'acne': 'warrgarrk marntara',
  'allergy': 'mayi jangany',
  'anemia': 'kungulu mayi',
  'anxiety': 'mangarli mayi',
  'arthritis': 'kuyuwarn pung',
  'asthma': 'ngayirrp ma-',
  'blood': 'kungulu',
  'bronchial': 'ngayirrp ma-',
  'cold': 'makurru',
  'cough': 'kulyurrk',
  'diarrhoea': 'jawuljaru',
  'disease': 'jangany',
  'fever': 'makurrmakurr',
  'food': 'mangarri',
  'fungal': 'warrgarrk marntara',
  'heart': 'mangarli',
  'infection': 'janga-yawung',
  'kidney': 'jiminkirt',
  'liver': 'malumpa',
  'migraine': 'ngarlaka pung',
  'pneumonia': 'ngayirrp ma-',
  'rash': 'warrgarrk marntara',
  'skin': 'warrgarrk',
  'sore': 'janga-yawung',
  'stomach': 'majul',
  'throat': 'ngirlkirri',
  'urinary': 'jiminkirt',
  'uti': 'jiminkirt jangany',
  'vomit': 'kurlpak yuwa-',
};

const _englishDiseaseLabels = <String, String>{
  'influenza': 'Fever and throat symptoms',
  'stomach upset': 'Stomach symptoms',
  'general symptoms': 'Pain or body discomfort',
  'urgent symptoms': 'Urgent chest, breathing, or bleeding signs',
};

const _englishGuidance = <String, List<String>>{
  'influenza': [
    'Rest and drink water.',
    'Use fever relief if it is safe for you.',
    'Visit the clinic if fever, throat pain, or weakness gets worse.',
    'Get urgent help if breathing becomes hard.',
  ],
  'stomach upset': [
    'Sip water often.',
    'Avoid heavy meals for now.',
    'Visit the clinic if pain or vomiting keeps going.',
    'Get urgent help if you cannot keep fluids down.',
  ],
  'general symptoms': [
    'Rest and watch for changes.',
    'Write down where it hurts and what changed.',
    'Visit the clinic if the pain keeps going or gets stronger.',
    'Get urgent help for chest pain, trouble breathing, or bleeding.',
  ],
  'urgent symptoms': [
    'Call 000 now.',
    'Get help from someone nearby if possible.',
    'Do not wait for the app if breathing, chest pain, or bleeding is severe.',
  ],
};

const _gurindjiGuidance = <String, List<String>>{
  'influenza': [
    'Yawarra.',
    'Mirrijin yamak nyawa.',
    'Nyangu-nyangu kawayi jangany warlarrp.',
    'Ngurra-ngkurra yamak.',
  ],
  'stomach upset': [
    'Yawarra.',
    'Mangarri yamak.',
    'Nyangu-nyangu kawayi jangany warlarrp.',
  ],
  'general symptoms': [
    'Yawarra.',
    'Jangany nyawa jala.',
    'Nyangu-nyangu kawayi jangany warlarrp.',
  ],
  'urgent symptoms': [
    '000 kawayi jala.',
    'SACA nyawa-wangu.',
    'Yamak karrinyana.',
  ],
};

const _englishConditionExplanations = <String, String>{
  'urgent symptoms':
      'These symptoms may need emergency care and should not wait.',
  'influenza':
      'Can match fever, headache, throat symptoms, or flu-like illness.',
  'stomach upset': 'Can match stomach pain, vomiting, nausea, or bloating.',
  'general symptoms': 'General pattern from the information provided.',
};

const _gurindjiConditionExplanations = <String, String>{
  'urgent symptoms': 'Warlarrp. 000 kawayi jala.',
  'influenza': 'Makurrmakurr, ngarlaka pung, ngirlkirri pung.',
  'stomach upset': 'Majul pung, kurlpak yuwa-, jawuljaru.',
  'general symptoms': 'Jangany nyawa jala.',
};
